[project]
name = "pydf-docs"
version = "0.1.0"
description = "Add a short description here"
authors = ["RenaudLN <renaudlaine31@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
dash = ">=2.17.0,<2.18"
plotly = ">=5.22.0,<5.23"
dash-mantine-components = ">=0.14.3,<0.15"
dash-iconify = ">=0.1.2,<0.2"
pydantic = ">=2.7.1,<2.8"
python-frontmatter = ">=1.1.0,<1.2"
ipykernel = ">=6.29.3,<6.30"
jupyterlab = ">=4.2.0,<4.3"
pixi-kernel = ">=0.3.0,<0.4"

[pypi-dependencies]
markdown2dash = "*"
dash-pydantic-form = "*"

[tool.pixi.pypi-dependencies]
pixi_py = { path = ".", editable = true }
